KH-Final-Team1/BookFinder_Backend

.gitignore, src/main/java/com/kh/bookfinder/entity/Book.java, src/main/java/com/kh/bookfinder/repository/BookRepository.java, src/test/java/com/kh/bookfinder/repository/BookRepositoryTest.java, src/test/java/com/kh/bookfinder/util/JsonParsingSqlTest.java, src/test/resources/insert.sql, src/test/resources/test.json
참고 #7  
- 도서관 인기 대출 API를 이용하여 200개의 책 데이터 셋을 json파일로 저장함
- 자바 코드로 API 요청한 것이 아닌 API 요청 도구 (Postman)을 사용
- json파일을 읽고 적절하게 sql파일로 변환함
- 도서관 인기 대출 API로 받은 응답 데이터에는 description과 publication_date가 없기 때문에 Book Table에는 null로 들어감
=> JH-7: Book Entity 추가

src/main/java/com/kh/bookfinder/entity/Address.java, src/main/java/com/kh/bookfinder/entity/User.java, src/main/java/com/kh/bookfinder/entity/UserStatus.java, src/main/java/com/kh/bookfinder/repository/AddressRepository.java, src/main/java/com/kh/bookfinder/repository/UserRepository.java, src/test/java/com/kh/bookfinder/repository/AddressRepositoryTest.java, src/test/java/com/kh/bookfinder/repository/UserRepositoryTest.java
#9 #13 
- Address 테이블이 꼭 필요한지 의문
- 그냥 주소는 String, Not null로 해도 괜찮을 것 같음
- 나중에 당근처럼 구나 동 단위로 게시판을 분류한다고 해도, 주소에 대한 테이블이 아니라 구나 동에 대한 테이블로 둬도 될 것 같음
=> JH-9: User, Address Entity 추가

src/main/java/com/kh/bookfinder/controller/BookTradeController.java, src/main/java/com/kh/bookfinder/dto/BookTradeDTO.java, src/main/java/com/kh/bookfinder/entity/BookTrade.java, src/main/java/com/kh/bookfinder/entity/Borough.java, src/main/java/com/kh/bookfinder/entity/Status.java, src/main/java/com/kh/bookfinder/entity/TradeType.java, src/main/java/com/kh/bookfinder/repository/BookTradeRepository.java, src/main/java/com/kh/bookfinder/repository/BoroughRepository.java, src/main/java/com/kh/bookfinder/service/BookService.java, src/main/java/com/kh/bookfinder/service/BookTradeService.java
#37 
---
- {boroughId}를 받아 해당하는 지역구의 거래글을 조회한다.
- 게시글이 없을 경우 빈 배열을 반환
- e0dcf086f79df04a46c928efae8948c4d155bcb3
=> KE-37: 사용자간 대출 게시글 조회 API 추가

src/main/java/com/kh/bookfinder/constants/Borough.java, src/main/java/com/kh/bookfinder/constants/Message.java, src/main/java/com/kh/bookfinder/controller/BookTradeController.java, src/main/java/com/kh/bookfinder/dto/BookTradeDTO.java, src/main/java/com/kh/bookfinder/repository/BookTradeRepository.java, src/main/java/com/kh/bookfinder/service/BookTradeService.java
#40 
- tradeId를 입력받아 해당 게시글 상세 내용 조회
=> KE-40: 사용자간 대출 게시글 상세조회

src/main/java/com/kh/bookfinder/constants/Message.java, src/main/java/com/kh/bookfinder/controller/BookTradeController.java, src/main/java/com/kh/bookfinder/dto/BookTradeDTO.java, src/main/java/com/kh/bookfinder/repository/BookTradeRepository.java, src/main/java/com/kh/bookfinder/service/BookTradeService.java
#38
- tradeId를 입력받아 해당 게시글 수정기능 추가
- 회원번호, 지역번호 관련 기능 추가 예정
- 삽입 / 수정 성공 시 삽입한 데이터를 return 할지 성공 여부 메세지를 return할지 고민중이라 수정 성공시는 Messasge를 보내주도록 구현했는데 다같이 이야기 해보고 둘중 하나 바꿔서 통일성있게 수정하겠습니다.
=> KE-38: 게시글 수정 기능 추가

src/main/java/com/kh/bookfinder/constants/Message.java, src/main/java/com/kh/bookfinder/controller/BookTradeController.java, src/main/java/com/kh/bookfinder/dto/BookTradeDTO.java, src/main/java/com/kh/bookfinder/repository/BookTradeRepository.java, src/main/java/com/kh/bookfinder/service/BookTradeService.java
#39 
- tradeId를 입력받아 해당 게시글 삭제 기능 추가
=> KE-39: 사용자간 대출 게시글 삭제

src/main/java/com/kh/bookfinder/constants/Message.java, src/main/java/com/kh/bookfinder/controller/BookController.java, src/main/java/com/kh/bookfinder/dto/SearchDto.java, src/main/java/com/kh/bookfinder/repository/BookRepository.java, src/main/java/com/kh/bookfinder/service/BookService.java
#48 
1. filter 설정 및 keyword를 받는다.
2. filter에 따라 keyword가 포함된 도서 목록의 배열을 반환한다.
=> DS-48: 도서 목록 조회 API 작성:

src/main/java/com/kh/bookfinder/constants/Message.java, src/main/java/com/kh/bookfinder/controller/BookController.java, src/main/java/com/kh/bookfinder/entity/Book.java, src/main/java/com/kh/bookfinder/repository/BookRepository.java, src/main/java/com/kh/bookfinder/service/BookService.java
<hr>
<a href="https://github.com/orgs/KH-Final-Team1/projects/1/views/1?pane=issue&itemId=61625774">#45</a>
<br>
<hr>
- filter와 keyword 입력받아 해당하는 도서 정보를 조회한다
- filter에 따라 keyword를 검색했는데 도서 정보가 안나온다면 404(Not Found)와 오류 메시지를 반환
- filter에 따라 keyword를 검색해서 도서 요청한 정보 목록이 나온다면 200(OK)와 도서 정보 목록을 반환
=> MS-45: 도서 요청 게시판 조회 API 작성: BookController, BookService, BookRepository 메소드 작성, Book에 approvalStatus Message에 NOT_FOUND_WAIT 상수 추가

src/main/java/com/kh/bookfinder/constants/Message.java, src/main/java/com/kh/bookfinder/controller/BookTradeController.java, src/main/java/com/kh/bookfinder/dto/BookTradeDto.java, src/main/java/com/kh/bookfinder/service/BookService.java, src/main/java/com/kh/bookfinder/service/BookTradeService.java
- 예외처리 코드 간결화
- Autowired → private final로 수정
- DTO명칭 Dto로 수정
=> KE-0: 리팩토링: book, bookTrade 예외처리 수정, DTO->Dto 명칭 수정

src/main/java/com/kh/bookfinder/book/controller/BookController.java, src/main/java/com/kh/bookfinder/book/dto/ApprovalStatusDto.java, src/main/java/com/kh/bookfinder/book/dto/SearchDto.java, src/main/java/com/kh/bookfinder/book/repository/BookRepository.java, src/main/java/com/kh/bookfinder/book/service/BookService.java, src/main/java/com/kh/bookfinder/global/constants/Message.java
<hr>
#73 
<hr>
- isbn과 approvalStatus를 입력받아 해당하는 도서의 승인 여부를 변경(수정)할 수 있다.
=> MS-73: 도서 요청 승인 거절 API 추가

src/main/java/com/kh/bookfinder/book/controller/BookController.java, src/main/java/com/kh/bookfinder/book/dto/ApprovalStatusDto.java, src/main/java/com/kh/bookfinder/book/dto/SearchDto.java, src/main/java/com/kh/bookfinder/book/entity/ApprovalStatus.java, src/main/java/com/kh/bookfinder/book/entity/Book.java, src/main/java/com/kh/bookfinder/book/repository/BookRepository.java, src/main/java/com/kh/bookfinder/book/service/BookService.java, src/main/java/com/kh/bookfinder/book_trade/controller/BookTradeController.java
- 승인 상태 (ApprovalStatus) : WAIT, APPROVE, REJECT
- 도서 최초 등록 시 상태 WAIT 로 설정
=> KE-0: 리팩토링: ApprovalStatus enum 클래스로 변경

src/main/java/com/kh/bookfinder/book/controller/BookController.java, src/main/java/com/kh/bookfinder/book/dto/BookRequestDto.java, src/main/java/com/kh/bookfinder/book/service/BookService.java, src/main/java/com/kh/bookfinder/global/constants/Message.java
#83 
- BookRequestDto를 받아 해당 도서의 Book 객체를 생성하고 저장한다.
=> MS-83: 도서 요청 등록 API 작성: BookController, Service 메서드 추가, Message 추가, BookRequestDto 추가

src/main/java/com/kh/bookfinder/book_trade/dto/BookTradeRequestDto.java, src/main/java/com/kh/bookfinder/comment/controller/CommentController.java, src/main/java/com/kh/bookfinder/comment/dto/CommentRequestDto.java, src/main/java/com/kh/bookfinder/comment/dto/CommentResponseDto.java, src/main/java/com/kh/bookfinder/comment/entity/Comment.java, src/main/java/com/kh/bookfinder/comment/repository/CommentRepository.java, src/main/java/com/kh/bookfinder/comment/service/CommentService.java, src/main/java/com/kh/bookfinder/global/constants/Message.java, src/main/java/com/kh/bookfinder/user/service/UserService.java
#41 #42 #43 #44 
- 댓글 조회
- 댓글 삭제
- 댓글 수정
- 댓글 삭제
- 로그인 기능 완성 시 사용자 정보 jwt로 받아서 저장하도록 수정 예정
- 댓글 수정 및 삭제 권한 검사 추가 예정
=> KE-44: 사용자간 대출 댓글 조회/등록/수정/삭제

src/main/java/com/kh/bookfinder/book/controller/BookController.java, src/main/java/com/kh/bookfinder/book/dto/BookRequestDto.java, src/main/java/com/kh/bookfinder/book/service/BookService.java
- 주소를 오직 request body로만 받게 하였고 BookService에서 requestBook 메소드를 추가하였습니다
=> MS-83: 리펙토링: BookController에 @PostMapping에 /request 주소 삭제

src/main/java/com/kh/bookfinder/auth/jwt/service/JwtService.java, src/main/java/com/kh/bookfinder/book_trade/repository/BoroughRepository.java, src/main/java/com/kh/bookfinder/user/entity/User.java
=> JH-102: Jwt의 Claim에 boroughId, userId 추가

src/main/java/com/kh/bookfinder/auth/config/SecurityConfig.java, src/main/java/com/kh/bookfinder/book_trade/controller/BookTradeController.java, src/main/java/com/kh/bookfinder/book_trade/service/BookTradeService.java, src/main/java/com/kh/bookfinder/comment/controller/CommentController.java, src/main/java/com/kh/bookfinder/comment/service/CommentService.java, src/main/java/com/kh/bookfinder/global/constants/Message.java, src/main/java/com/kh/bookfinder/global/exception/GlobalExceptionHandler.java, src/main/java/com/kh/bookfinder/global/exception/UnauthorizedException.java, src/main/java/com/kh/bookfinder/user/service/UserService.java
- 글, 댓글 작성 시 userId가 저장되도록 수정
- 댓글 api 로그인 권한 받도록 수정
- 글, 댓글 수정 / 삭제 / 상태 변경 시 해당 글 작성자만 변경 가능하도록 수정
- UnauthorizedException 추가
- 글 작성 시 사용자 지역 정보 받아와서 추가되도록 수정 예정
=> KE-97: 거래 관련 기능 사용자 인증

build.gradle, src/main/java/com/kh/bookfinder/book_trade/dto/BookTradeDetailResponseDto.java, src/main/java/com/kh/bookfinder/book_trade/dto/BookTradeListResponseDto.java, src/main/java/com/kh/bookfinder/book_trade/entity/BookTrade.java, src/main/java/com/kh/bookfinder/book_trade/repository/BookTradeRepository.java, src/main/java/com/kh/bookfinder/user/controller/ServiceUserController.java, src/main/java/com/kh/bookfinder/user/dto/MyInfoResponseDto.java, src/main/java/com/kh/bookfinder/user/entity/User.java, src/main/java/com/kh/bookfinder/user/service/UserService.java, src/test/java/com/kh/bookfinder/book_trade/helper/MockBookTrade.java, src/test/java/com/kh/bookfinder/user/api/GetMyUserInfoApiTest.java, src/test/java/com/kh/bookfinder/user/api/SignUpApiTest.java, src/test/java/com/kh/bookfinder/user/helper/MockUser.java
https://github.com/orgs/KH-Final-Team1/projects/1/views/1?pane=issue&itemId=64242650
#106
=> JH-106: 내 정보 조회 API 추가

build.gradle, src/main/java/com/kh/bookfinder/auth/config/SecurityConfig.java, src/main/java/com/kh/bookfinder/auth/jwt/filter/JwtAuthenticationFilter.java, src/main/java/com/kh/bookfinder/auth/jwt/service/JwtService.java, src/main/java/com/kh/bookfinder/book_trade/dto/BookTradeDetailResponseDto.java, src/main/java/com/kh/bookfinder/book_trade/dto/BookTradeListResponseDto.java, src/main/java/com/kh/bookfinder/book_trade/entity/BookTrade.java, src/main/java/com/kh/bookfinder/book_trade/repository/BookTradeRepository.java, src/main/java/com/kh/bookfinder/global/constants/Message.java, src/main/java/com/kh/bookfinder/user/controller/ServiceUserController.java, src/main/java/com/kh/bookfinder/user/dto/MyInfoResponseDto.java, src/main/java/com/kh/bookfinder/user/entity/User.java, src/main/java/com/kh/bookfinder/user/service/UserService.java, src/test/java/com/kh/bookfinder/auth/jwt/JwtAuthenticationFilterTest.java, src/test/java/com/kh/bookfinder/auth/jwt/JwtAuthorizationFilterTest.java, src/test/java/com/kh/bookfinder/book_trade/helper/MockBookTrade.java, src/test/java/com/kh/bookfinder/user/api/GetMyUserInfoApiTest.java, src/test/java/com/kh/bookfinder/user/api/SignUpApiTest.java, src/test/java/com/kh/bookfinder/user/helper/MockUser.java
=> JH-108: jwt auth 테스트코드 추가

src/main/java/com/kh/bookfinder/book/dto/SearchDto.java, src/main/java/com/kh/bookfinder/book/repository/BookRepository.java, src/main/java/com/kh/bookfinder/book/service/BookService.java
- Service: WAIT, REJECT인 도서를 조회
- Repository: 메서드명 변경
- SearchDto에 page, size 추가
=> MS-45: 도서 요청 게시판 리팩토링

src/main/java/com/kh/bookfinder/book/dto/SearchDto.java, src/main/java/com/kh/bookfinder/book/repository/BookRepository.java, src/main/java/com/kh/bookfinder/book/service/BookService.java
#117 
- 도서 요청 게시판 API 부분만
- List -> Page 변경
- Service, Rpository에 Pageable 추가SearchDto에 page, size 추가
=> MS-117: 도서 리스트 리팩토링

src/main/java/com/kh/bookfinder/book_trade/controller/BookTradeController.java, src/main/java/com/kh/bookfinder/book_trade/dto/BookTradeRequestDto.java, src/main/java/com/kh/bookfinder/book_trade/service/BookTradeService.java, src/main/java/com/kh/bookfinder/global/constants/Message.java, src/test/java/com/kh/bookfinder/book_trade/CreateBookTradeApiTest.java, src/test/java/com/kh/bookfinder/book_trade/GetBookTradeOneApiTest.java, src/test/java/com/kh/bookfinder/book_trade/ListBookTradeApiTest.java, src/test/java/com/kh/bookfinder/book_trade/UpdateBookTradeApiTest.java, src/test/java/com/kh/bookfinder/helper/MockBook.java, src/test/java/com/kh/bookfinder/helper/MockUser.java, src/test/java/com/kh/bookfinder/helper/RequestDto.java
=> JH-116: Update BookTrade API 테스트코드 추가

src/main/java/com/kh/bookfinder/book_trade/controller/BookTradeController.java, src/main/java/com/kh/bookfinder/book_trade/dto/BookTradeRequestDto.java, src/main/java/com/kh/bookfinder/book_trade/dto/BookTradeYnDto.java, src/main/java/com/kh/bookfinder/book_trade/service/BookTradeService.java, src/main/java/com/kh/bookfinder/global/constants/Message.java, src/test/java/com/kh/bookfinder/book_trade/ChangeBookTradeStatusApiTest.java, src/test/java/com/kh/bookfinder/book_trade/CreateBookTradeApiTest.java, src/test/java/com/kh/bookfinder/book_trade/GetBookTradeOneApiTest.java, src/test/java/com/kh/bookfinder/book_trade/ListBookTradeApiTest.java, src/test/java/com/kh/bookfinder/book_trade/UpdateBookTradeApiTest.java, src/test/java/com/kh/bookfinder/helper/MockBook.java, src/test/java/com/kh/bookfinder/helper/MockUser.java, src/test/java/com/kh/bookfinder/helper/RequestDto.java
=> JH-120: Change Book Trade Status API 테스트코드 추가

src/main/java/com/kh/bookfinder/book_trade/controller/BookTradeController.java, src/main/java/com/kh/bookfinder/book_trade/dto/BookTradeRequestDto.java, src/main/java/com/kh/bookfinder/book_trade/dto/BookTradeYnDto.java, src/main/java/com/kh/bookfinder/book_trade/entity/BookTrade.java, src/main/java/com/kh/bookfinder/book_trade/service/BookTradeService.java, src/main/java/com/kh/bookfinder/global/constants/Message.java, src/main/java/com/kh/bookfinder/user/entity/User.java, src/test/java/com/kh/bookfinder/book_trade/ChangeBookTradeStatusApiTest.java, src/test/java/com/kh/bookfinder/book_trade/CreateBookTradeApiTest.java, src/test/java/com/kh/bookfinder/book_trade/DeleteBookTradeApiTest.java, src/test/java/com/kh/bookfinder/book_trade/GetBookTradeOneApiTest.java, src/test/java/com/kh/bookfinder/book_trade/ListBookTradeApiTest.java, src/test/java/com/kh/bookfinder/book_trade/UpdateBookTradeApiTest.java, src/test/java/com/kh/bookfinder/helper/MockBook.java, src/test/java/com/kh/bookfinder/helper/MockUser.java, src/test/java/com/kh/bookfinder/helper/RequestDto.java
=> JH-122: Delete BookTrade API 테스트코드 추가

src/main/java/com/kh/bookfinder/auth/config/SecurityConfig.java, src/main/java/com/kh/bookfinder/book/controller/BookController.java, src/main/java/com/kh/bookfinder/book/dto/BookCreateRequestDto.java, src/main/java/com/kh/bookfinder/book/service/BookService.java, src/main/java/com/kh/bookfinder/global/constants/Message.java, src/test/java/com/kh/bookfinder/book/api/CreateBookApiTest.java, src/test/java/com/kh/bookfinder/helper/RequestDto.java
- 테스트 코드 추가
- Dto 클래스 유효성 검사 추가
- 인증된 User만 요청 가능하도록 수정
- 중복에 대한 Status Code 409로 수정
- 성공에 대한 Status Code 201로 수정
=> JH-126: Create Book API 수정:

src/main/java/com/kh/bookfinder/auth/config/SecurityConfig.java, src/main/java/com/kh/bookfinder/auth/jwt/handler/JwtForbiddenHandler.java, src/main/java/com/kh/bookfinder/auth/jwt/handler/JwtUnauthorizedHandler.java, src/main/java/com/kh/bookfinder/book/controller/BookController.java, src/main/java/com/kh/bookfinder/book/dto/BookUpdateStatusRequestDto.java, src/main/java/com/kh/bookfinder/book/service/BookService.java, src/main/java/com/kh/bookfinder/global/constants/Message.java, src/test/java/com/kh/bookfinder/book/api/UpdateBookApprovalStatusApiTest.java, src/test/java/com/kh/bookfinder/helper/RequestDto.java
- 테스트 코드 추가
- Admin 권한만 가능하도록 수정
- Path Variable, Request Body Validation 추가
- JwtFailureHandler 분기 처리
=> JH-130: Update Book Status API 수정
